//const plugin = require('tailwindcss/plugin');

module.exports = {
  content: [],
  theme: {
    fontFamily: {
      sans: ['Gilroy-SemiBold'],
      heading: ['Gilroy-Bold'],
      med: ['Gilroy-Medium'],
      reg: ['Gilroy-Regular'],
      thin: ['Gilroy-Thin'],
      titleBranch: ['Branch'],
    },
    extend: {
      borderRadius: {
        30: 30,
        20: 20,
        15: 15,
        10: 10,
      },
      colors: {
        background: '#F5F6FA',
        primary: '#FF9100',
        black: '#313244',
        lightBlack: '#2F2F2F',
        lightGray: '#F5F5F5',
        selectedGray: '#F2F3F6',
        descGray: '#7A7A8A',
        basicGray: '#C9C2DD',
        disable: '#828486',
        grayBorder: '#717171',
        grayBg: '#D9D9D9',
        lightPink: '#DEA0AF',
        basicGreen: '#00C851',
        basicYellow: '#FFC700',
        basicPurple: '#7B62B9',
        basicRed: '#FF614C',
      },
      fontSize: {
        10: '10px',
        '1.5xl': [
          '22px',
          {
            //letterSpacing: '-0.01em',
            lineHeight: '26px',
          },
        ],
        '4.5xl': [
          '40px',
          {
            //letterSpacing: '-0.01em',
            lineHeight: '50px',
          },
        ],
      },
    },
  },
  plugins: [
    // plugin(({addUtilities}) => {
    //   addUtilities({
    //     page: 'flex flex-1 bg-background flex-col px-4 py-6',
    //     'tp-heading': 'font-heading text-lg text-zinc-900',
    //     'tp-titleBranch': 'font-titleBranch text-3xl text-primary',
    //     'tp-lead1': 'font-med text-sm text-zinc-900',
    //     'tp-lead2': 'font-med text-base text-zinc-900',
    //     'tp-body1': 'font-sans text-base text-gray-600',
    //     'tp-body2': 'font-sans text-sm text-gray-600',
    //     'tp-body3': 'font-sans text-xs text-gray-600',
    //     'tp-small1': 'font-sans text-sm text-gray-600',
    //     'tp-small2': 'font-sans text-xs text-gray-600',
    //     //added
    //     'bv-sans-xs': 'font-sans text-xs text-black',
    //     'bv-sans-sm': 'font-sans text-sm text-black',
    //     'bv-sans-base': 'font-sans text-base text-black',
    //     'bv-sans-lg': 'font-sans text-lg text-black',
    //     'bv-sans-xl': 'font-sans text-xl text-black',
    //     'bv-sans-1.5xl': 'font-sans text-1.5xl text-black',
    //     'bv-heading-xs': 'font-heading text-xs text-black',
    //     'bv-heading-sm': 'font-heading text-sm text-black',
    //     'bv-heading-base': 'font-heading text-base text-black',
    //     'bv-heading-lg': 'font-heading text-lg text-black',
    //     'bv-heading-xl': 'font-heading text-xl text-black',
    //     'bv-heading-1.5xl': 'font-heading text-1.5xl text-black',
    //     'bv-med-xs': 'font-med text-xs text-black',
    //     'bv-med-sm': 'font-med text-sm text-black',
    //     'bv-med-base': 'font-med text-base text-black',
    //     'bv-med-lg': 'font-med text-lg text-black',
    //     'bv-med-xl': 'font-med text-xl text-black',
    //     'bv-med-1.5xl': 'font-med text-1.5xl text-black',
    //     'bv-reg-xs': 'font-reg text-xs text-black',
    //     'bv-reg-sm': 'font-reg text-sm text-black',
    //     'bv-reg-base': 'font-reg text-base text-black',
    //     'bv-reg-lg': 'font-reg text-lg text-black',
    //     'bv-reg-xl': 'font-reg text-xl text-black',
    //     'bv-reg-1.5xl': 'font-reg text-1.5xl text-black',
    //     'bv-thin-xs': 'font-thin text-xs text-black',
    //     'bv-thin-sm': 'font-thin text-sm text-black',
    //     'bv-thin-base': 'font-thin text-base text-black',
    //     'bv-thin-lg': 'font-thin text-lg text-black',
    //     'bv-thin-xl': 'font-thin text-xl text-black',
    //     'bv-thin-1.5xl': 'font-thin text-1.5xl text-black',
    //   });
    // }),
  ],
};
